#!/usr/bin/env python3
import os
import re
import sys

def parse_markdown_section(content, section_name):
    """
    Extracts the content of a markdown section by name.
    """
    pattern = rf"##\s+{re.escape(section_name)}\s*\n(.*?)(?=\n##\s+|$)"
    match = re.search(pattern, content, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return ""

def compile_spec(b_item_path, spec_output_path="SPEC.md"):
    allowed_dir = os.path.abspath(os.getcwd())
    target_path = os.path.abspath(spec_output_path)
    if not target_path.startswith(allowed_dir):
        print("Error: Output path must be within the workspace.", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(b_item_path):
        print(f"Error: B-Item file not found at '{b_item_path}'", file=sys.stderr)
        sys.exit(1)
        
    with open(b_item_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Extract Title (h1)
    title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else "Unnamed Backlog Item"

    # Extract standard Megaplan B-item sections
    outcome = parse_markdown_section(content, "Business outcome") or parse_markdown_section(content, "Outcome")
    scope = parse_markdown_section(content, "Scope")
    test_plan = parse_markdown_section(content, "Test plan")
    criteria = parse_markdown_section(content, "Verification & Acceptance Criteria") or parse_markdown_section(content, "Acceptance criteria")

    spec_content = f"""# Agent Task Specification: {title}

> [!IMPORTANT]
> This SPEC.md was dynamically compiled from {os.path.basename(b_item_path)}.
> DO NOT edit this file manually. Any changes should be made to the source backlog item.

## 1. Objective & Business Outcome
{outcome if outcome else "No business outcome defined."}

## 2. In-Scope Requirements
{scope if scope else "No explicit scope defined."}

## 3. Success & Verification Criteria
{criteria if criteria else "No acceptance criteria defined."}

## 4. Test Plan & Execution
{test_plan if test_plan else "No test plan defined."}

## 5. Agent Boundaries & Constraints
* Only edit files directly in-scope for this deliverable.
* Do not delete or rename existing configuration files unless explicitly directed above.
* Always run the verification tests before declaring the task complete.
"""

    with open(spec_output_path, "w", encoding="utf-8") as f:
        f.write(spec_content)
    
    print(f"Successfully compiled '{b_item_path}' -> '{spec_output_path}'")

def main():
    if len(sys.argv) < 2:
        print("Usage: compile_spec.py <path_to_b_item.md> [output_spec_path]")
        sys.exit(1)
        
    b_item_path = sys.argv[1]
    spec_output_path = sys.argv[2] if len(sys.argv) > 2 else "SPEC.md"
    compile_spec(b_item_path, spec_output_path)

if __name__ == "__main__":
    main()
