#!/usr/bin/env python3
import os
import re
import sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from _mdparse import find_repo_root, parse_front_matter, parse_markdown_section

WIKI_CONTEXT_MAX_PAGES = 3
WIKI_CONTEXT_MAX_LINES = 150


def build_wiki_context(repo_root, item_content):
    """Return an optional '## 6. Prior Context (AI Wiki)' section, or "".

    Deterministic feed-forward: pulls architecture/notes pages whose `module`
    slug is mentioned in this B-item, bounded so Layer 1's context-limiting
    purpose survives. Returns "" when no wiki exists or nothing matches.
    """
    wiki_dir = os.path.join(repo_root, "docs", "megaplan", "wiki")
    if not os.path.isdir(wiki_dir):
        return ""

    haystack = item_content.lower()
    candidates = []
    for sub in ("architecture", "notes"):  # most useful as prior context
        d = os.path.join(wiki_dir, sub)
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if not name.endswith(".md"):
                continue
            page_path = os.path.join(d, name)
            with open(page_path, "r", encoding="utf-8") as f:
                page = f.read()
            meta, body = parse_front_matter(page)
            module = (meta.get("module") or "").strip().lower()
            if module and module in haystack:
                rel = os.path.relpath(page_path, wiki_dir)
                candidates.append((rel, body.strip()))

    if not candidates:
        return ""

    blocks = []
    line_budget = WIKI_CONTEXT_MAX_LINES
    for rel, body in candidates[:WIKI_CONTEXT_MAX_PAGES]:
        body_lines = body.split("\n")
        if len(body_lines) > line_budget:
            body_lines = body_lines[:line_budget] + ["", "*(truncated)*"]
        line_budget -= len(body_lines)
        blocks.append(f"### From `wiki/{rel}`\n" + "\n".join(body_lines))
        if line_budget <= 0:
            break

    return (
        "\n## 6. Prior Context (AI Wiki)\n"
        "> Injected from the AI wiki as background — derived and possibly stale. "
        "The code and source docs win on any conflict.\n\n"
        + "\n\n".join(blocks)
        + "\n"
    )


def compile_spec(b_item_path, spec_output_path="SPEC.md"):
    repo_root = find_repo_root(start=os.path.dirname(os.path.abspath(__file__)))
    allowed_dir = os.path.realpath(repo_root)
    target_path = os.path.realpath(spec_output_path)

    # Path traversal validation for output path (resolving symlinks)
    if os.path.commonpath([allowed_dir, target_path]) != allowed_dir:
        raise ValueError("Output path must be within the workspace.")

    # Path traversal validation for input path (resolving symlinks)
    input_path = os.path.realpath(b_item_path)
    if os.path.commonpath([allowed_dir, input_path]) != allowed_dir:
        raise ValueError("Input B-Item path must be within the workspace.")

    if not os.path.exists(input_path):
        raise ValueError(f"B-Item file not found at '{b_item_path}'")

    # Ensure output parent directory exists
    target_dir = os.path.dirname(target_path)
    if target_dir:
        os.makedirs(target_dir, exist_ok=True)

    with open(input_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Extract Title (h1)
    title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else "Unnamed Backlog Item"

    # Extract standard Megaplan B-item sections
    outcome = parse_markdown_section(
        content, "Business outcome"
    ) or parse_markdown_section(content, "Outcome")
    scope = parse_markdown_section(content, "Scope")
    test_plan = parse_markdown_section(content, "Test plan")
    criteria = parse_markdown_section(
        content, "Verification & Acceptance Criteria"
    ) or parse_markdown_section(content, "Acceptance criteria")

    spec_content = f"""# Agent Task Specification: {title}

> [!IMPORTANT]
> This SPEC.md was dynamically compiled from {os.path.basename(input_path)}.
> DO NOT edit this file manually. Any changes should be made to the source backlog item.

## 1. Objective & Business Outcome
{outcome if outcome else "No business outcome defined."}

## 2. In-Scope Requirements
{scope if scope else "No explicit scope defined."}

## 3. Success & Verification Criteria
{criteria if criteria else "No acceptance criteria defined."}

## 4. Test Plan & Execution
{test_plan if test_plan else "No test plan defined."}

## 5. Agent Boundaries & Constraints
* Only edit files directly in-scope for this deliverable.
* Do not delete or rename existing configuration files unless explicitly directed above.
* Always run the verification tests before declaring the task complete.
"""

    spec_content += build_wiki_context(repo_root, content)

    with open(target_path, "w", encoding="utf-8") as f:
        f.write(spec_content)

    print(f"Successfully compiled '{b_item_path}' -> '{spec_output_path}'")


def main():
    if len(sys.argv) < 2:
        print("Usage: compile_spec.py <path_to_b_item.md> [output_spec_path]")
        sys.exit(1)

    b_item_path = sys.argv[1]
    spec_output_path = sys.argv[2] if len(sys.argv) > 2 else "SPEC.md"
    try:
        compile_spec(b_item_path, spec_output_path)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
